### ISSUE TITLE
[bug]现在工具已经无法运行了

### ISSUE THREAD

**Issue by zhongqingsong** [dyglcc/reverseToy#3]
兄弟，你这个项目好久没维护了。然后，我第一步就不行了，apktool反编译这一步就失败了。
你有空吗，更新下apktool到最新版的呢。
或者，能告知下怎么升级你这个里面的apktool。直接把apktool复制过来就行吗，还是你改动了apktool的源码？

PS F:\Some> java -jar .\reversetoy.jar reverse m .\TastyBlue.apk .\libMetaX-release.aar .\code_json_default-adhoc.txt
I: apk file name F:\Some\.\TastyBlue.apk
I: Loading resource table...
I: Baksmaling classes.dex...
java.lang.IllegalArgumentException: character to be escaped is missing
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1019)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)
        at java.base/java.lang.String.replaceAll(String.java:2939)
        at com.appadhoc.reversetoy.aar.AarManager.getRjavaFile(AarManager.java:195)
        at com.appadhoc.reversetoy.aar.AarManager.compileRfile2class(AarManager.java:201)
        at com.appadhoc.reversetoy.aar.AarManager.unzipAarAndCreateTmpApk(AarManager.java:145)
        at com.appadhoc.reversetoy.MultiSDKs.dealWithSDKpackages(MultiSDKs.java:46)
        at com.appadhoc.reversetoy.Main.reverse(Main.java:126)
        at brut.apktool.Main.cmdMerge(Main.java:140)
        at brut.apktool.Main.main(Main.java:89)
I: Loading resource table...
I: merge arsc file ...
I: merge AndroidManifest.xml to F:\Some\.\TastyBlue\AndroidManifest.xml
brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/windows/jar.exe
        at com.appadhoc.reversetoy.utils.Utils$BuildPackage.getJarComm(Utils.java:713)
        at com.appadhoc.reversetoy.aar.AarManager.rClass2jar(AarManager.java:434)
        at com.appadhoc.reversetoy.aar.AarManager.smaliClass(AarManager.java:407)
        at com.appadhoc.reversetoy.aar.AarManager.smaliClassFilesAndModifyids(AarManager.java:323)
        at com.appadhoc.reversetoy.MultiSDKs.dealWithSDKpackages(MultiSDKs.java:52)
        at com.appadhoc.reversetoy.Main.reverse(Main.java:126)
        at brut.apktool.Main.cmdMerge(Main.java:140)
        at brut.apktool.Main.main(Main.java:89)
Caused by: brut.common.BrutException: Could not extract resource: /prebuilt/windows/jar.exe
        at brut.util.Jar.extractToTmp(Jar.java:90)
        at brut.util.Jar.extractToTmp(Jar.java:69)
        at brut.util.Jar.getResourceAsFile(Jar.java:39)
        at com.appadhoc.reversetoy.utils.Utils$BuildPackage.getJarComm(Utils.java:708)
        ... 7 more
Caused by: java.io.FileNotFoundException: /prebuilt/windows/jar.exe
        at brut.util.Jar.extractToTmp(Jar.java:80)
        ... 10 more

**Comment by dyglcc** [comment]
抱歉，最近一段时间忙其他事情了，没有时间看这个项目！我看到程序堆栈信息，大概是这个jar工具没有配置好吧，请先将windows命令行下jar环境配置好再试试

**Comment by zhongqingsong** [comment]
"java -jar .\reversetoy.jar reverse m .\TastyBlue.apk .\libMetaX-release.aar .\code_json_default-adhoc.txt"
这个就是我的命令行，本机是有Java环境的喔。是还有那个要操作的吗？

**Comment by dyglcc** [comment]
你好，首先你的命令行 有问题，正确的命令行是，java -jar apktool-reverseToy.jar m abc.apk libs reverse_code_json_default-adhoc.txt ，请检查你的命令行代码。
其次，错误堆栈信息就是jar命令执行的错误，我的macOS环境下没有报错这个错误，而且我这里没有windows环境，等我有时间搞个window环境来看一下

**Comment by zhongqingsong** [comment]
> 你好，首先你的命令行 有问题，正确的命令行是，java -jar apktool-reverseToy.jar m abc.apk libs reverse_code_json_default-adhoc.txt ，请检查你的命令行代码。 其次，错误堆栈信息就是jar命令执行的错误，我的macOS环境下没有报错这个错误，而且我这里没有windows环境，等我有时间搞个window环境来看一下

我改了下命令行了，按照你的那个命令行的格式（有.\这个是win的要求，不是错误指令）。然后运行后，直接反编译到清单文件时就报错了。能帮忙看下原因吗？

F:\Some\libraries\2> java -jar .\reversetoy.jar m .\Ty.apk .\M_0830.aar .\reverse_code_json_default-adhoc.txt
I: apk file name F:\Some\libraries\2\.\Ty.apk
I: Loading resource table...
I: Baksmaling classes.dex...
W: F:\Some\libraries\2\.\aar\tmp0b9f5\M_0830\AndroidManifest.xml:9: error: No resource identifier found for attribute 'requestLegacyExternalStorage' in package 'android'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_931273664190870731.tmp, package, -f, -m, -J, F:\Some\libraries\2\.\aar\tmp0b9f5\rFiles, -F, F:\Some\libraries\2\.\aar\tmp0b9f5\aar_tmp.apk, -S, F:\Some\libraries\2\.\aar\tmp0b9f5\M_0830\res, -I, C:\Users\admin\AppData\Local\Temp\brut_util_Jar_12648182139218766832.tmp, -M, F:\Some\libraries\2\.\aar\tmp0b9f5\M_0830\AndroidManifest.xml]
        at com.appadhoc.reversetoy.utils.Utils$OSCMD.runCMD(Utils.java:60)
        at com.appadhoc.reversetoy.aar.AarManager.aaptAarPackageNew(AarManager.java:318)
        at com.appadhoc.reversetoy.aar.AarManager.unzipAarAndCreateTmpApk(AarManager.java:143)
        at com.appadhoc.reversetoy.MultiSDKs.dealWithSDKpackages(MultiSDKs.java:46)
        at com.appadhoc.reversetoy.Main.reverse(Main.java:126)
        at brut.apktool.Main.cmdMerge(Main.java:140)
        at brut.apktool.Main.main(Main.java:89)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_931273664190870731.tmp, package, -f, -m, -J, F:\Some\libraries\2\.\aar\tmp0b9f5\rFiles, -F, F:\Some\libraries\2\.\aar\tmp0b9f5\aar_tmp.apk, -S, F:\Some\libraries\2\.\aar\tmp0b9f5\M_0830\res, -I, C:\Users\admin\AppData\Local\Temp\brut_util_Jar_12648182139218766832.tmp, -M, F:\Some\libraries\2\.\aar\tmp0b9f5\M_0830\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:173)
        at com.appadhoc.reversetoy.utils.Utils$OSCMD.runCMD(Utils.java:56)
        ... 6 more
java.nio.file.NoSuchFileException: F:\Some\libraries\2\.\aar\tmp0b9f5\aar_tmp.apk
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at com.appadhoc.reversetoy.utils.Utils$FileUtils.getZipEntryFile(Utils.java:71)
        at com.appadhoc.reversetoy.utils.Utils.findArsc(Utils.java:48)
        at com.appadhoc.reversetoy.aar.AarManager.mergeArscFile(AarManager.java:164)
        at com.appadhoc.reversetoy.MultiSDKs.dealWithSDKpackages(MultiSDKs.java:48)
        at com.appadhoc.reversetoy.Main.reverse(Main.java:126)
        at brut.apktool.Main.cmdMerge(Main.java:140)
        at brut.apktool.Main.main(Main.java:89)

**Comment by androidcyw** [comment]
兄弟，你解决了吗？我这边用这个工具也是报错

**Comment by zhongqingsong** [comment]
> 兄弟，你解决了吗？我这边用这个工具也是报错

没有，放弃了。感觉高版本的Android这些功能有点小问题。而且 最关键的resID的合并问题，你知道怎么处理不？
